#### Ques 1. Create a vector with values ranging from 10 to 49 


In [11]:
import numpy as np
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Ques 2.  Reverse a vector (first element becomes last)


In [12]:
import numpy as np
a = np.arange(11)
a = a[::-1]
print(a)

[10  9  8  7  6  5  4  3  2  1  0]


####  Ques 3.Create a 3x3 identity matrix

In [1]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Ques 4. Create a 10x10 array with random values and find the minimum and maximum values

In [4]:
import numpy as np
r = np.random.randint(2,100,(10,10))
r

array([[35, 54, 58, 34, 39, 70, 29, 29,  3, 94],
       [36, 64, 99, 42, 58, 36, 11, 32, 24, 27],
       [92, 71, 23, 54, 60, 89, 64, 29, 17, 75],
       [75,  3, 19, 44, 63, 44, 70, 34, 44, 72],
       [45, 43,  3, 29, 48, 12,  3, 19, 93, 53],
       [49, 54, 61, 64, 86, 50, 12, 80, 45, 34],
       [72, 19, 83, 27, 23, 52, 36, 36, 78, 41],
       [99, 17, 50, 43, 58,  3, 66, 43, 97, 75],
       [75, 12, 11, 24, 14, 48, 75, 28, 34, 96],
       [52, 90, 42, 55, 91, 48, 46, 14, 69, 39]])

In [8]:
r.min()


3

In [7]:
r.max()

99

#### Ques 5.What is the result of the following expression?
#### 0 * np.nan
#### np.nan == np.nan
#### np.inf > np.nan
#### np.nan - np.nan
#### np.nan in set([np.nan])
#### 0.3 == 3 * 0.1


In [13]:
import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### Ques 6.How to sum a small array faster than np.sum? 

In [18]:
import numpy as np
a = np.arange(10,50)
np.add.reduce(a)

1180

#### Ques 7.How to find the closest value (to a given scalar) in a vector?

In [21]:
import numpy as np
x = np.arange(100)
print("Original array:")
print(x)
a = np.random.uniform(0,100)
print("Value to compare:")
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Value to compare:
61.352670276848656
61
